new container2 building

diff --git a/Containers/dbatoolswof2/dockerfile b/Containers/dbatoolswof2/dockerfile
--- a/Containers/dbatoolswof2/dockerfile
+++ b/Containers/dbatoolswof2/dockerfile
@@ -1,17 +1,51 @@
-FROM dbachecks/sqlinstance3
+###
+#
+#   temp/builder image: add users, logins, databases, etc
+#
+###
+
+# get the latest SQL container and set it as the builder image
+FROM mcr.microsoft.com/mssql/server:2022-latest as builder
+
+# switch to root to a bunch of stuff that requires elevated privs
 USER root
 
-# some cleanup
-RUN apt-get autoremove -y \
-    && apt-get clean -y
+# set the pwd and chown to the service account
+WORKDIR /tmp
+RUN chown mssql /tmp
 
-# Install dbatools prerelease
-SHELL ["/usr/bin/pwsh", "-c"]
-RUN $ErrorActionPreference='Stop'; Install-Module -Name dbatools -Force -AllowPreRelease;
+# copy scripts and make bash files executable
+# use copy instead of add, it's safer apparently
+COPY sql scripts /tmp/
+RUN chmod +x /tmp/*.sh
 
-# set the dbatools config to not require encryption - change in SMO
-SHELL ["/usr/bin/pwsh", "-c"]
-RUN Set-DbatoolsConfig -Name sql.connection.trustcert -Value $true -passthru | Register-DbatoolsConfig; Set-DbatoolsConfig -Name sql.connection.encrypt -Value $false -passthru | Register-DbatoolsConfig
+# convert CRLF to LF in case Windows or VS Code changed it
+RUN find . -type f \( -name "*.sql" -o -name "*.env" -o -name "*.sh" \) -exec sed -i 's/\r$//' {} \;
 
-SHELL ["/usr/bin/pwsh", "-c"]
-RUN /opt/mssql/bin/mssql-conf set hadr.hadrenabled  1; 
+# switch to user mssql or the container will fail
+USER mssql
+
+# run initial setup scripts
+RUN /bin/bash /tmp/start-sql.sh
+
+###
+#
+#   final image: grab the good stuff, label
+#   the image, and startup the sql instance
+#
+###
+
+# copy the required changed files from "builder"
+# and use it to start from scratch
+FROM mcr.microsoft.com/mssql/server:2022-latest
+COPY --from=builder /var/opt/mssql /var/opt/mssql
+COPY --from=builder /opt/mssql-tools/bin /opt/mssql-tools/bin
+
+# make a shared dir with the proper permissions
+USER root
+RUN  mkdir /shared; chown mssql /shared
+
+# run a rootless container
+USER mssql
+ENTRYPOINT /opt/mssql/bin/sqlservr
+# CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
